# Generated by Django 2.1.1 on 2018-09-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=200)),
                ('news_date', models.DateTimeField(verbose_name='date published')),
                ('news_url', models.CharField(max_length=200)),
            ],
        ),
    ]
