# Generated by Django 2.1.1 on 2018-09-08 11:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='news_text',
            field=models.CharField(default=datetime.datetime(2018, 9, 8, 11, 22, 42, 775833, tzinfo=utc), max_length=200000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new',
            name='news_type',
            field=models.IntegerField(default=1),
        ),
    ]
