# Generated by Django 2.1.1 on 2018-09-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180908_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=200)),
                ('video_url', models.CharField(max_length=200)),
                ('video_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
