# Generated by Django 2.1.1 on 2018-09-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='news_text',
        ),
        migrations.RemoveField(
            model_name='new',
            name='news_type',
        ),
        migrations.RemoveField(
            model_name='new',
            name='news_url',
        ),
    ]
