# Generated by Django 2.1.1 on 2018-09-14 02:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180914_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='news_type',
            field=models.CharField(default=datetime.datetime(2018, 9, 14, 2, 27, 35, 63720, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
